/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package multipleTutorial;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class complexStruct implements org.apache.thrift.TBase<complexStruct, complexStruct._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("complexStruct");

  private static final org.apache.thrift.protocol.TField SOME_STRING_FIELD_DESC = new org.apache.thrift.protocol.TField("someString", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new complexStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new complexStructTupleSchemeFactory());
  }

  public String someString; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SOME_STRING((short)1, "someString");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SOME_STRING
          return SOME_STRING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SOME_STRING, new org.apache.thrift.meta_data.FieldMetaData("someString", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(complexStruct.class, metaDataMap);
  }

  public complexStruct() {
  }

  public complexStruct(
    String someString)
  {
    this();
    this.someString = someString;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public complexStruct(complexStruct other) {
    if (other.isSetSomeString()) {
      this.someString = other.someString;
    }
  }

  public complexStruct deepCopy() {
    return new complexStruct(this);
  }

  @Override
  public void clear() {
    this.someString = null;
  }

  public String getSomeString() {
    return this.someString;
  }

  public complexStruct setSomeString(String someString) {
    this.someString = someString;
    return this;
  }

  public void unsetSomeString() {
    this.someString = null;
  }

  /** Returns true if field someString is set (has been assigned a value) and false otherwise */
  public boolean isSetSomeString() {
    return this.someString != null;
  }

  public void setSomeStringIsSet(boolean value) {
    if (!value) {
      this.someString = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SOME_STRING:
      if (value == null) {
        unsetSomeString();
      } else {
        setSomeString((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SOME_STRING:
      return getSomeString();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SOME_STRING:
      return isSetSomeString();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof complexStruct)
      return this.equals((complexStruct)that);
    return false;
  }

  public boolean equals(complexStruct that) {
    if (that == null)
      return false;

    boolean this_present_someString = true && this.isSetSomeString();
    boolean that_present_someString = true && that.isSetSomeString();
    if (this_present_someString || that_present_someString) {
      if (!(this_present_someString && that_present_someString))
        return false;
      if (!this.someString.equals(that.someString))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(complexStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    complexStruct typedOther = (complexStruct)other;

    lastComparison = Boolean.valueOf(isSetSomeString()).compareTo(typedOther.isSetSomeString());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSomeString()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.someString, typedOther.someString);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("complexStruct(");
    boolean first = true;

    sb.append("someString:");
    if (this.someString == null) {
      sb.append("null");
    } else {
      sb.append(this.someString);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (someString == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'someString' was not present! Struct: " + toString());
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class complexStructStandardSchemeFactory implements SchemeFactory {
    public complexStructStandardScheme getScheme() {
      return new complexStructStandardScheme();
    }
  }

  private static class complexStructStandardScheme extends StandardScheme<complexStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, complexStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SOME_STRING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.someString = iprot.readString();
              struct.setSomeStringIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, complexStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.someString != null) {
        oprot.writeFieldBegin(SOME_STRING_FIELD_DESC);
        oprot.writeString(struct.someString);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class complexStructTupleSchemeFactory implements SchemeFactory {
    public complexStructTupleScheme getScheme() {
      return new complexStructTupleScheme();
    }
  }

  private static class complexStructTupleScheme extends TupleScheme<complexStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, complexStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.someString);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, complexStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.someString = iprot.readString();
      struct.setSomeStringIsSet(true);
    }
  }

}

